### ISSUE TITLE
Avoid changing function input objects

### ISSUE THREAD

**Issue by kbariotis** [ryanmcdermott/clean-code-javascript#108]
A thing I see very often is when we are changing a function's object variables. Those variables are passed by reference and this is a side effect. I would propose of adding it to the Side Effects section.

**Comment by ryanmcdermott** [comment]
Oh yes definitely! The Avoid Side Effects subsection is quite possibly the most important of everything in this project. We could have Part 2 to this. Want to open a PR? :smile:

**Comment by petetnt** [comment]
👍 

This is also exhibited in the earlier samples themselves and should be cleaned up from places like:
https://github.com/ryanmcdermott/clean-code-javascript#dont-add-unneeded-context
https://github.com/ryanmcdermott/clean-code-javascript#function-names-should-say-what-they-do
https://github.com/ryanmcdermott/clean-code-javascript#set-default-objects-with-objectassign

**Comment by ryanmcdermott** [comment]
Great point Pete! Let's go all in if we double down on being side-effectless.
