### ISSUE TITLE
Script to extract JavaScript fragments from a markdown file

### ISSUE THREAD

**Issue by vsemozhetbyt** [ryanmcdermott/clean-code-javascript#113]
Most likely there are many better solutions for this, but here it is [my quick attempt](https://gist.github.com/vsemozhetbyt/d714bf98f4235a77db923e1c8744bc1b).

Usage: `md.extract-js.js markdown-file.md`.

Extracted `.js` files will be created in the `markdown-file.md.extracted-js` directory next to `markdown-file.md`. Each file has this name template: `numberOfFragment.numberOfFirstLine-numberOfLastLine.js`.

A contributor can run a linter on the whole directory or run each file with Node.js. There will be many linter errors or runtime errors due to many undeclared (or unused) variables, so some filter work will be needed.

In our case, the odd filenames are bad examples, the even filenames are good ones.

Here is [a new PR](https://github.com/ryanmcdermott/clean-code-javascript/pull/114) from this script's work.

**Comment by vsemozhetbyt** [comment]
In our case, the odd filenames are bad examples, the even filenames are good ones.

**Comment by vsemozhetbyt** [comment]
Here is [a new PR](https://github.com/ryanmcdermott/clean-code-javascript/pull/114) from this script's work.

**Comment by ryanmcdermott** [comment]
Hey this is a cool script! This could be expanded upon to be used as part of a code testing suite too for this project. I think having real working code here is a thing to aim for!

**Comment by ryanmcdermott** [comment]
Closing for now, would love to see the script as its own project, cool stuff!

**Comment by vsemozhetbyt** [comment]
@ryanmcdermott There is [an ESLint plugin for js in markdown](https://github.com/eslint/eslint-plugin-markdown) from the ESLint team itself!
