### ISSUE TITLE
"Use method chaining" and Law of Demeter

### ISSUE THREAD

**Issue by aaronmcadam** [ryanmcdermott/clean-code-javascript#125]
I think this part of the guide falls into the trap of thinking that the Law of Demeter (LOD) is simply about multiple method calls or the "2/3 dot rule". 

It's more about "not talking to strangers". The paper ["The Paperboy, The Wallet and The Law Of Demeter"](http://www.ccs.neu.edu/research/demeter/demeter-method/LawOfDemeter/paper-boy/demeter.pdf) sums it up nicely.

 If your functions return the same type, it's totally fine. In your example, you're using the builder pattern, which always returns the same type to allow further operations.

Another example of not violating LOD would be a functional pipeline transforming an array:

```js
const list = [1, 2, 3, 4, 5]

list.map(...).reduce(...).filter(...).concat(...) // not a violation of LOD
```

Hope this helps!

**Comment by ryanmcdermott** [comment]
Hey Aaron! You know what, you're totally right. I have removed it. Thanks for your help! d97805d66e0b5c5cc0973c970b07aa4e21e6013d
