### ISSUE TITLE
Default arguments

### ISSUE THREAD

**Issue by rubenmoya** [ryanmcdermott/clean-code-javascript#129]
We should add some disclaimer in the "default arguments" section, since the example will work only if the argument passed is `undefined`, if the argument is null, it won't work in the second example, but it will work in the first one.

**Comment by ryanmcdermott** [comment]
Hey there! There's a PR for this, and I think I'll probably add a small disclaimer to keep short-circuiting if you expect `falsey` values other than `undefined`. https://github.com/ryanmcdermott/clean-code-javascript/pull/106
