### ISSUE TITLE
Destructuring array will error if no match

### ISSUE THREAD

**Issue by Hainesy** [ryanmcdermott/clean-code-javascript#130]
`const [, city, zipCode] = address.match(cityZipCodeRegex);`

This will error if the address doesn't match, but can be fixed with:

`const [, city, zipCode] = address.match(cityZipCodeRegex) || [];`

**Comment by ryanmcdermott** [comment]
Cool! Can you make a PR?

**Comment by Endlessline** [comment]
I did

**Comment by Hainesy** [comment]
Ah you beat me to it, sorry.
