### ISSUE TITLE
Mutation testing

### ISSUE THREAD

**Issue by simondel** [ryanmcdermott/clean-code-javascript#131]
What are your thoughts on mutation testing?

**Background info:**
Mutation testing is a technique used to measure the quality of your tests. Code coverage only measures which code is executed during testing, mutation testing actually _tests your tests_. This is done by inserting bugs (mutations) into your code such as replacing `>` with `<` or `>=`.  

After a mutation has been applied to the code, all tests belonging to that mutation are executed. If a tests fails due to mutated code, all is well. Your tests managed to detect the bug. If no tests failed, you may have an issue.

The current guide says:
> **the main point is** to just make sure you are **reaching your coverage goals** before launching any feature  

This does not mean that you have properly tested your application. Unfortunately there are people who temporarily disable assertions, only to forget to turn them back on again. Sometimes **people even write tests without assertions** (or bad ones) just for the sake of reaching their code coverage goals.

So, what are the downsides of mutation testing (in JavaScript)?

- It's (relatively) slow because tests have to be executed many, many times.
- It's hard to write a mutation testing framework for JavaScript. There are a lot of combinations of compilers, test frameworks and test runners.

**Comment by ryanmcdermott** [comment]
Looking back now after writing the *Testing* section, it seems that the code coverage comment has led people astray. I don't mean to say it's a silver bullet, it's just a necessary but insufficient condition to a stable codebase. I just assumed due diligence in writing good tests, as per following the rest of the guide's suggestions for testing.

Want to improve the *Testing* section to say something a little more accurate about code coverage?

**Comment by simondel** [comment]
I believe mutation testing is vital to properly testing your application. Do you mind if I talk about it as well?

**Comment by ryanmcdermott** [comment]
It's a cool area, but I'm torn: I don't want to stray too far from Clean Code though, but Robert C. Martin has written about it in a positive light: http://blog.cleancoder.com/uncle-bob/2016/06/10/MutationTesting.html

**Comment by simondel** [comment]
The book Clean Code? That was last published in 2008 as far as I know. That's almost 10 years ago. Mutation testing has really been getting traction in the last two or so years.

**Comment by ryanmcdermott** [comment]
I totally understand where you're coming from, it's a cool newer idea. The issue I have is that there are plenty of engaging ideas we could pursue and recommend here, but the great thing about Clean Code, which this project is based upon, is that the ideas are older and have tons of anecdotal experience to back them up. I think one reason that this project has intrigued some people is that it feels that there are always new things that JavaScript is drawing upon, but the older and more finally polished ideas seem to be missing from guides and resources. Hopefully my position makes sense, thank you for your understanding!

**Comment by nicojs** [comment]
@ryanmcdermott I agree with you, but you could still mention that code coverage isn't the holy grail. Focusing on code coverage could become a bad practice in itself. For example, it could lead to tests without assertions. You could at least mention mutation testing as a way to prevent that from happening.

To a larger extend is see that there is no mention about the level of abstraction to use when testing. I'm talking about the testing pyramid. Would you agree that that should be part of the clean code on javascript? If so, would you mind me having a crack at it?
