### ISSUE TITLE
Open/Closed Principle (OCP) example

### ISSUE THREAD

**Issue by krzysztof-grzybek** [ryanmcdermott/clean-code-javascript#133]
I think Open/Closed Principle is not about ability to extend module functionality during app runtime. It's more about writing code which doesn't require from developers changing existing code during adding new functionality. I thought about this example and I think it could be slightly changed. Let's say we have class responsible for fetch data, handle response and return promise. It can be configured to use in both browser and node js environment. This could be bad example:

```js
class AjaxAdapter extends Adapter {
  constructor() {
    super();
    this.name = 'ajaxAdapter';
  }
}

class NodeAdapter extends Adapter {
  constructor() {
    super();
    this.name = 'nodeAdapter';
  }
}

class httpRequester {
  constructor(adapter) {
    this.adapter = adapter;
  }

  fetch(url) {
    if (this.adapter.name === 'ajaxAdapter') {
      return makeAjaxCall(url).then(response => {
        // transform response and return
      });
    } else if(this.adapter.name === 'httpNodeAdapter') {
      return makeHttpCall(url).then(response => {
        // transform response and return
      });
    }
  }
}

function makeAjaxCall(url) {
  // request and return promise
}

function makeHttpCall(url) {
  // request and return promise
}
```

This is bad, because if we would like to add new adapter, we have to change httpRequester class. We can fix it this way:

```js
class AjaxAdapter extends Adapter {
  constructor() {
    super();
    this.name = 'ajaxAdapter';
  }

  request(url) {
    // request and return promise
  }
}

class NodeAdapter extends Adapter {
  constructor() {
    super();
    this.name = 'nodeAdapter';
  }

  request(url) {
    // request and return promise
  }
}

class httpRequester {
  constructor(adapter) {
    this.adapter = adapter;
  }

  fetch(url) {
    return this.adapter.request(url).then(response => {
      // transform response and return
    });
  }
}
```

What do You think about that ?

**Comment by vsemozhetbyt** [comment]
@krzysztof-grzybek You could improve readability of your examples by wrapping them in MarkDown tags like this:
<pre>
```js
// the code
```
</pre>

**Comment by vsemozhetbyt** [comment]
(It seems [`super()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/super) before `this` is forgotten in some constructors)

**Comment by krzysztof-grzybek** [comment]
@vsemozhetbyt thank You, both issues fixes :)

**Comment by ryanmcdermott** [comment]
Good point, in my example adding an HTTP_METHOD at runtime isn't exactly the _best_ demonstration of OCP, although technically it's valid. I like yours better though! Can you make a PR?

**Comment by krzysztof-grzybek** [comment]
Sure ! :)
