### ISSUE TITLE
Variable - Use meaningful and pronounceable variable names - yearMonthDay is Not meaningful

### ISSUE THREAD

**Issue by ChenReuven** [ryanmcdermott/clean-code-javascript#136]
yearMonthDay is Not meaningful name.

birthday, holiday name, that a meaningful name for a date.
yearMonthDay is just a format name and if the implementation is change a bit the name will also change.

what do you think?

Thanks :)

**Comment by ryanmcdermott** [comment]
Hey Chen!

True, those are more meaningful than `yearMonthDay`. That's only the case if those actually match up to a current instance of a `moment` object. What's always valid, and perhaps more meaningful, is `todayYearMonthDay`. It's a little verbose, but it's very clear. Maybe we can do better though. On Pg. 50, Clean Code gives a much better example that we can probably go to for JavaScript, excuse the lack of formatting: 

**Bad**
```java
public List<int[]> getThem() {
List<int[]> list1 = new ArrayList<int[]>(); for (int[] x : theList)
if (x[0] == 4) list1.add(x);
return list1; }
```

**Good**
```java
public List<Cell> getFlaggedCells() {
List<Cell> flaggedCells = new ArrayList<Cell>(); for (Cell cell : gameBoard)
if (cell.isFlagged()) flaggedCells.add(cell);
return flaggedCells; }
```

**Comment by ChenReuven** [comment]
Mmm so maybe currentDate, todayDate its a bit more clear and less verbose. Regard to the flagged cell i agree :-)

**Comment by ryanmcdermott** [comment]
Cool, I've changed it to this for now! b1b37eb23421f54a705f00fe4be756dd39339158

**Comment by dsherret** [comment]
This is a huge nitpick... in my opinion, `currentDate` sounds like the name of a variable that holds a moment or Date object. It doesn't give any indication that it's a formatted date string. I would expect `currentDate` to just be `const currentDate = moment()`.

I think the example could be improved by instead doing:

```typescript
const d = moment(); // bad
const currentDate = moment(); // good
```

Ideally though, I think it would be even better to come up with an example that doesn't depend on a js library.
