### ISSUE TITLE
Never, never, have duplicate code... really?

### ISSUE THREAD

**Issue by danielfoxp2** [ryanmcdermott/clean-code-javascript#138]
Well, as Sandy Metz beautifully has shown us [here](https://www.youtube.com/watch?v=8bZh5LMaSmE) and [here](https://www.sandimetz.com/blog/2016/1/20/the-wrong-abstraction), "duplication is far cheaper than the wrong abstraction".

So be careful.

**Comment by ryanmcdermott** [comment]
This was handled here: 3364af5f98722eedc9f60c47e6c67bafad7acf43

Thanks!
