### ISSUE TITLE
Translation to pt-BR

### ISSUE THREAD

**Issue by esganzerla** [ryanmcdermott/clean-code-javascript#146]
Hello,

I started translating this guide to pt-BR, if anyone would like to help I'm doing it at: (https://github.com/esganzerla/clean-code-javascript/blob/master/translations/pt-BR/README.md)

Thanks

**Comment by fesnt** [comment]
Hey, I started a translate too a week ago, it was referenced in this issue #55.
The three last chapters are not finished yet.

**Comment by esganzerla** [comment]
@fesnt cool, i tried searching here but didn't find. I'll fork your repository!
