### ISSUE TITLE
Ternary Operators

### ISSUE THREAD

**Issue by donsingh** [ryanmcdermott/clean-code-javascript#150]
What's the standard for Ternary Operators? I find that I use them a lot in my js code. Back in college we used to have these rules:

1. Absolutely 1 condition only
2. Atomic data in the true/false section
3. The ternary statement is in its own line, not nesting between other statements.

**Comment by ryanmcdermott** [comment]
Ternaries are fine, though Clean Code doesn't go into them. If you want a good style specific explanation the AirBnB style guide has some great stuff to say on the matter: https://github.com/airbnb/javascript#comparison--nested-ternaries
https://github.com/airbnb/javascript#comparison--unneeded-ternary

As for readability, reusability, and refactorability: it doesn't have too big of an effect on developers being able to work with your codebase, unless your team really just HATES them. In that case, write a linting rule to prevent them!
