### ISSUE TITLE
disagree with 'Don't over-optimize'

### ISSUE THREAD

**Issue by sevencai** [ryanmcdermott/clean-code-javascript#158]
![qq 20170119200848](https://cloud.githubusercontent.com/assets/23190922/22106482/e3a9d462-de83-11e6-9df9-ac4d77475dcc.png)

The time log shows us that maybe it's better to calculate the length and store it .

From 0.065ms to 0.035ms.

**Comment by sevencai** [comment]
Sorry that I did't see `In modern browsers, this is optimized.`;

**Comment by w3cmark** [comment]
Why is it closed, so the result is whether modern browsers are optimized?
The results of my tests were also not found to be optimized(chrome 73.0.3683.103):

![image](https://user-images.githubusercontent.com/7434649/56946702-73c60a80-6b5d-11e9-80f0-b3acf7159cda.png)

**Comment by andreyluiz** [comment]
default: 2.386962890625ms
default: 1.27099609375ms

**Comment by andreyluiz** [comment]
I performed the same test with the same Chrome version and there is a big difference, really.
