### ISSUE TITLE
Would recommend destructuring in function args 2 or less

### ISSUE THREAD

**Issue by bali182** [ryanmcdermott/clean-code-javascript#159]
This is absolutely not helpful, when you are trying to find out what kind of keys do the `config` object accept.

```js
function createMenu(config) {
  // ...
}

createMenu({
  title: 'Foo',
  body: 'Bar',
  buttonText: 'Baz',
  cancellable: true
});
```

This however makes it perfectly clean exactly which keys are used:

```js
function createMenu({ title, body, buttonText, cancellable }) {
  // ...
}
```

There are no sneaky magic properties accessed in the call chain later, since you don't have the reference to the original `config` object. I would highly recommend suggesting this version. Also while coding, if you have a linter, it will tell you if you have an unused prop in the destrucutured object while it will have no chance of warning you if you just take it as a regular argument.

**Comment by ryanmcdermott** [comment]
Cool, that makes the method signature easier to understand. Want to make a PR?
