### ISSUE TITLE
Modularize the huge markdown file

### ISSUE THREAD

**Issue by bali182** [ryanmcdermott/clean-code-javascript#162]
Since there are open issues with people translating the big markdown file - #55 #99  #146 ..., it would be a shame to have all the code duplicated in all of them. We could create a folder with all the snippets which could be then included by the different translation. It could be done, with

* remark - https://github.com/wooorm/remark
* remark-include - https://github.com/Qard/remark-include
* an additional transpilation step

I would like to create a PR if you are willing to include this in your repo, but it will be consist of a huge amount of changes and a lot to review. Let me know!

**Comment by fesnt** [comment]
Nice idea, but what about the comments that are made into the code? I think that it is helpul to translate that. it is possible with these tools?

**Comment by bali182** [comment]
No, if the code has moving parts as well that has to be translated, then the whole idea is worthless...

**Comment by ryanmcdermott** [comment]
This is a compelling idea, although I've been trying to keep to AirBnB's style guide format. I'm going to close this for now but if I change my mind about this I'll reopen this! Thanks for thinking about this!
