### ISSUE TITLE
[section] "Don't over optimize" explanation

### ISSUE THREAD

**Issue by lnfnunes** [ryanmcdermott/clean-code-javascript#163]
Reference: [dont-over-optimize](https://github.com/ryanmcdermott/clean-code-javascript#dont-over-optimize)

Since all examples are using ES6+, arguing about old browsers don't looks significant IMHO.
Maybe another argument should be better. What do you think?

**Comment by ryanmcdermott** [comment]
You're right that the example is older, but it's one that some JavaScript developers who started with the language a while back will recognize as an old optimization. It's no longer a needed optimization, and the central point of this subsection is to suggest that you should see if you're doing anything like this currently in your code, but is actually already browser-optimized. See my project on typed arrays for example: https://github.com/ryanmcdermott/typed-arrays
