### ISSUE TITLE
Variables with similar names prone to typing mistakes?

### ISSUE THREAD

**Issue by zurfyx** [ryanmcdermott/clean-code-javascript#168]
Let's say you have `location` and `locations` one next to each other, could this to lead to typing errors if you mistakenly write an extra `s`?

The closest I found in [clean-code-javascript](https://github.com/ryanmcdermott/clean-code-javascript) was [Avoid Mental Mapping](https://github.com/ryanmcdermott/clean-code-javascript#avoid-mental-mapping):

```
locations.forEach((location) => {
  ...
});
```

In the previous example, a proper editor (or its extension) could rapidly find out that `location` is not being used if you only used `locations` instead.

But what about in the following case?

```
function processLocationByExploringOtherLocations(location, locations) {
  ...
}
```

location and locations have the exact same priority for any editor, should we use something like `locationsList` instead?

Also, I am well aware that in this case [TypeScript](https://github.com/Microsoft/TypeScript) or [flow](https://github.com/facebook/flow) would have recognized a typing mistake by simple checking their type. However, there are still many projects which do not use either of them.

**Comment by artityod** [comment]
https://github.com/ryanmcdermott/clean-code-javascript/commit/00a50681b1c0a24e9c8c08d8872fee9c76da17d5

**Comment by ryanmcdermott** [comment]
For sure you are right, that's one big problem I have with JavaScript and why I've subtly advocated TypeScript in this guide 😉  I think we should leave this subsection in, despite the verbosity and accident-propensity it may possess.
