### ISSUE TITLE
Not explicit function name

### ISSUE THREAD

**Issue by AnnaNee** [ryanmcdermott/clean-code-javascript#175]
In section [Function names should say what they do](https://github.com/ryanmcdermott/clean-code-javascript#function-names-should-say-what-they-do) you're explicitly saying that you're adding a **month** to a date, `addMonthToDate()`.

In section [Remove duplicate code](https://github.com/ryanmcdermott/clean-code-javascript#remove-duplicate-code) you're showing the employees list using `showList()`.

Shouldn't that be showEmployeesList() as well, in order to explicitly tell what will be shown, so you just have to pass the type of the employee as an argument (managers or developers in that context)?

I'm not really sure about it, which is why I wanted to discuss about. Thanks for this great work!

**Comment by ryanmcdermott** [comment]
You know what, you're right. It should say showEmployeesList! Want to make a PR?

**Comment by AnnaNee** [comment]
Sure!

**Comment by huei90** [comment]
The other examples give

`showDeveloperList` without (s)
`showManagerList` without (s)

and now we use `showEmployessList` with (s)

which is the best case?

**Comment by AnnaNee** [comment]
Haven't thought about that. I usually use in the plural form when a certain method has many properties as a result, so `showEmployeesList ()`. But to talk about the best practices I can't say which is better. In the other hand, in order to keep consistency, I think we should change to `showEmployeeList()`.

What you think?

**Comment by ryanmcdermott** [comment]
This gets into a bit of linguisitics, which is off in the weeds away from Clean Code, but a noun pre-modifier is usually singular: Grocery List, Customer List, Client List, etc. I think `showEmployeeList` would be both consistent with the document and with the language 🤓 I could be comfortable with either, but let's just make it consistent then. Thanks for putting so much time into picking good names! Half of programming skill is about naming and organization.

**Comment by huei90** [comment]
> Half of programming skill is about naming and organization.

😂  indeed.

I also agree with either, as long as your team approve with the naming.

**Comment by AnnaNee** [comment]
I'll change it to `showEmployeeList()` then. Thanks @hueitan for pointing that out. ;)
