### ISSUE TITLE
"Interface Segregation Principle (ISP)" incorrect code in an example

### ISSUE THREAD

**Issue by Voronar** [ryanmcdermott/clean-code-javascript#185]
```js
// BAD
class DOMTraverser {
  constructor(settings) {
    this.settings = settings;
    this.setup();
  }

  setup() {
    this.rootNode = this.settings.rootNode;
    this.animationModule.setup(); // "this.animationModule" is undefined in class instance
  }

  traverse() {
    // ...
  }
}

const $ = new DOMTraverser({
  rootNode: document.getElementsByTagName('body'),
  animationModule() {} // Most of the time, we won't need to animate when traversing.
  // ...
});
```

```DOMTraverser``` class instance does not assign ```animationModule``` from a configuration object with its own ```animationModule``` field. For this reason ```this.animationModule.setup();``` is an incorrect peace of code. Did you assume ```this.settings.animationModule.setup();```?

**Comment by ryanmcdermott** [comment]
Check out this PR for more! https://github.com/ryanmcdermott/clean-code-javascript/pull/189
