### ISSUE TITLE
Question about two principles

### ISSUE THREAD

**Issue by Roar1827** [ryanmcdermott/clean-code-javascript#23]
I often find myself choosing between **Don't use flags as function parameters** and **Remove duplicate code**.

In the example for **Don't use flags as function parameters** we have as the suggested approach:
```js
function createTempFile(name) {
  fs.create('./temp/' + name);
}

function createFile(name) {
  fs.create(name);
}
```

This has duplicated code (although just 1 line in this case) in the same way that the bad example for **Remove duplicate code** has:
```js
function showDeveloperList(developers) {
...
    var githubLink = developer.getGithubLink();
...
}

function showManagerList(managers) {
...
    var portfolio = manager.getMBAProjects();
...
}
```

In the **Remove duplicate code** case we are suggested to instead do:
```js
function showList(employees) {
...
    if (employee.type === 'manager') {
      portfolio = employee.getMBAProjects();
    } else {
      portfolio = employee.getGithubLink();
    }
...
}
```

My question is, how do you decide when to keep code DRY, or to keep functions only doing 1 thing (not multiple variations of 1 thing = many things)?

I'd love some thoughts on this. Thanks!

**Comment by rkichenama** [comment]
```javascript
function createTempFile(name) {
  fs.create('./temp/' + name);
}

function createFile(name) {
  fs.create(name);
}
```

can be refactored to

```javascript
function createFile(name) {
  fs.create(name);
}

function createTempFile(name) {
  createFile('./temp/' + name);
}
```

**Comment by ryanmcdermott** [comment]
Refactored, thank you Richard!

3ea61da2e9197e6d31cee47fd6dbc4037fe192c4
