### ISSUE TITLE
STOP!!!!  READ THE BOOK OR WATCH THE VIDS FIRST

### ISSUE THREAD

**Issue by dschinkel** [ryanmcdermott/clean-code-javascript#236]
Yep that was an all caps title.  Because I want this to stand out.
 
The reason for my rant is:

**1)** because I have colleagues reading this list **before** they read UB's book or watch his vids because they think they can short circuit learning this stuff by doing so.  And I keep telling them that they need to do that **first**.  You mention nothing of the sort (an important call to action to do that!)

**2)** there are things in here that do not align with the concepts UB talks about because they're not given a wholistic view on many of the examples in here.  They are based on **biases**.  Devs need to understand it from the **concepts** first...from the view of UB first because that's solid ground to walk from first.

**3)** there are so many important subtle concepts UB talks about that are not mentioned here that are very important if people aren't reading his stuff first

@ryanmcdermott But you need to state that.  That devs need to not read this list and read the book or watch vids first rom UB.

> Like many rules herein, there is no hard and fast rule that you must follow.

the problem with your statement is that people need to get the context and lack of information from UB first.  People shouldn't be getting rules from a summarized version of clean code like this that can set people up for missing context on the subjects in the book.

Devs just coming and reading your list are missing half the stuff UB talks about which are very important and they might be reading things wrong in here and might infer things that UB would have clearly explained and with important info not stated in here.  Clean code is not meant to be read as "just another list of good practices".  There are so many things in here missing I can't even begin to figure out where to start.

People need to slow down, read his book, or watch vids on cleancoders.com and first get this from the source, UB.

There also things in here which are totally not what the clean code book would recommend, here's one:

```
const menuConfig = {
 title: 'Order',
 // User did not include 'body' key
 buttonText: 'Send',
 cancellable: true
};

```
Seriously?  comment there?  Why?  No.   That comment is totally unnecessary.  Clean code book would have said no comments, they're unnecessary here, they add friction to reading the code, can get out of date, or provide disinformation.  If you think you need a comment there, it's probably because you need to explain it some other way via another function, or the caller or whatever.

```
  setColor(color) {
    this.color = color;
    // NOTE: Returning this for chaining
    return this;
  }
```
why is there a note there?  completely goes against what UB talks about in many ways

```
function hashIt(data) {
  let hash = 0;
  const length = data.length;

  for (let i = 0; i < length; i++) {
    const char = data.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;

    // Convert to 32-bit integer
    hash &= hash;
  }
}
```
as simple as that line is, hash &= hash should be moved to a function that self describes...remove the comment

Comments cause friction, period.  There might be once in a blue moon that you'd need to add a comment but those are cases maybe like **algorithms** or for example like UB talks about [here](http://blog.cleancoder.com/uncle-bob/2017/02/23/NecessaryComments.html).

Now if people would have watched his vid or read his book, they'd see that this isn't really written like "well written Pros", hell it doesn't even read well to me even if I didn't watch his vids or read the clean code book:

`if (isDOMNodePresent(node)) {`

So..you're asking a question? if (some question?) . I see this a lot, that sounds stupid.  Try:

`if (domNodeIsPresent(node)) {`

That reads like normal english, unbroken.  Would I ask someone `if(are you going to the store?)` .   That doesn't even read right.

Using is as part of the name of a bool is fine, but not in all cases.  In this case it sounds like someone who can't speak proper english.

**All caps on constants still?**  I get that it infers something but your IDE should be telling you that it's a const and honestly if you feel the need to have that many global constants you should try to think why you have that many in the first place!  It's probably a hint that you need to decouple and modularize your code more.  To me all caps causes friction when you read code.

**DRY**.  Your section on this which is often the case misses the point of DRY.  It's not just about repeated code.  Kent Beck even talks about this in his famous TDD book.  UB sets that kind of stuff straight in his book / vids.

And what about **smaller functions should have longer names**, ect.  There's a reason for that, it's not just a rule he throws out there as just another bland rule.  That's one of many points  UB talks about in the very beginning, that's not even mentioned here at all.  There are so many important points.  **You can't just summarize Clean Code like this** and call it a day. People should read about or watch Names & Functions for example from UB first.

Anyway it bothers me that people are just coming here rather than reading the book or watching the vids.  And it bothers me you don't state that.

They're missing a ton of things that a list can't give you.  And people need to get this stuff straight from the source first and need to get that language independent first and understant it in general terms, not JS terms.  It's ok if they want to come back here but there are some things in here which still doesn't align with what UB says in his book or vids.

I honestly wish this list wasn't here.  Because I bet 90% of the 16,000 people subscribed to this repo haven't watched his vids, or read his book and won't because they'll think this is a shortcut to it and covers it.  I want people to get **all** of it from the **source** then **apply**. 

Clean Code isn't meant to read like a list.  UB does list concepts at the end of his vids and book chapters, but people need to read it in full to get better/well-rounded context and info from UB first...and use the lists of things UB talks about at the end of his vids.  Some of those things are in here, some of them are not but all of them are important and should be **heard** from UB first.  Nobody talks about this stuff like UB does.  

While I know you are not saying don't read UB's book or watch vids, I'm saying you need to be explicit about that up front, first sentence in your readme.

I applaud your intention and efforts, but I would not be using this list...period if I was a dev who has not read the book; there are too many things I'm seeing that are not mentioned, or don't align with the important **concepts** UB explains **clearly** and with a lot more context in his text/vids.

[There is already a clean code forum out there, run by UB himself](https://groups.google.com/forum/#!forum/clean-code-discussion), for people to throw up code examples anyway and to hash things around that way after people read the book or watch cleancoders.com vids.

**Comment by ryanmcdermott** [comment]
Thank you for your impassioned response to this project. You're right, I think it's worth mentioning that the book should be read and this is not a *complete* replacement for reading the primary source. I'm happy to address your other comments in a PR. Thanks!
