### ISSUE TITLE
Armenian translation

### ISSUE THREAD

**Issue by hanumanum** [ryanmcdermott/clean-code-javascript#241]
Hi, can your pls. add armenian translation to translations list ?

https://github.com/hanumanum/clean-code-javascript

**Comment by AliwerErgashev** [comment]
sorry, I do not know armenian

2018-04-29 19:03 GMT+05:00 Հանուման <notifications@github.com>:

**Comment by hanumanum** [comment]
I have already make translation, pls just add my repository link to list of translations :)
https://github.com/hanumanum/clean-code-javascript

**Comment by ryanmcdermott** [comment]
Can you open a PR and I'll add it to the list?
