### ISSUE TITLE
Use camelcase or uppercase?

### ISSUE THREAD

**Issue by goldEli** [ryanmcdermott/clean-code-javascript#249]
## Use searchable names

Good:
```
// Declare them as capitalized named constants.
const MILLISECONDS_IN_A_DAY = 86400000;

setTimeout(blastOff, MILLISECONDS_IN_A_DAY);
```
## Use explanatory variables

Good:
```
const address = 'One Infinite Loop, Cupertino 95014';
const cityZipCodeRegex = /^[^,\\]+[,\\\s]+(.+?)\s*(\d{5})?$/;
const [, city, zipCode] = address.match(cityZipCodeRegex) || [];
saveCityZipCode(city, zipCode);
```
`MILLISECONDS_IN_A_DAY` is uppercase,
But `cityZipCodeRegex` and `address` are camelcase?

**Comment by jasp402** [comment]
your observation is correct, it must be uppercase. It is a simpler way to organize the code and see it cleaner.
I think it should be corrected, even check the consistency of the book. everything should be coherent

[Use explanatory variables](https://github.com/ryanmcdermott/clean-code-javascript#table-of-contents)

**Comment by janakhpon** [comment]
yup .. UPPERCASE is pretty much clear to review
