### ISSUE TITLE
Opionion on `Function arguments`

### ISSUE THREAD

**Issue by gillchristian** [ryanmcdermott/clean-code-javascript#25]
> Zero arguments is the ideal case.

I don't think zero arguments is ideal, because it only applies to impure functions and objects or classes methods.

_Actually pure functions might have zero arguments, but they would be kind of pointless right?_

Since the guide favors single purpose pure functions, having zero arguments wouldn't make sense. In my opinion one argument is the ideal. And zero is just ok if the function is not pure or is a method of an object or class.

_Just an opionion._

**Comment by ryanmcdermott** [comment]
Thanks for chiming in here! In general your opinion is true. If you have a zero argument function, chances are that you're mutating something somewhere. However, it's sometimes the case that a function will calculate something or generate some large object in memory and return it to the caller. There's a good discussion on a related PR. I'll close this issue and we can discuss it more in there :) Suffice it to say, I'm quite happy to just say zero or one arguments are ideal (and if you are going zero then make sure you're not mutating something in a silly way!) https://github.com/ryanmcdermott/clean-code-javascript/pull/12
