### ISSUE TITLE
Spanish translations

### ISSUE THREAD

**Issue by tureey** [ryanmcdermott/clean-code-javascript#252]
I forked the repo and I'm translating this `README` to Spanish so more people can read it! ❤️

**Comment by GMaiolo** [comment]
I'd like to help.
What is the desired approach for translations, a different branch for each language?
Ping @ryanmcdermott

**Comment by leviatan21** [comment]
I like this idea!
Couple times I see a roo folder for translations
EJ: root/lang/spanish/README.MD

**Comment by tureey** [comment]
Shit haha I'm almost finished. 😂
I forked the project and I was going to share link with @ryanmcdermott
I couldn't push yet to my repo because I have no internet (I am traveling) @leviatan21 @GMaiolo

**Comment by ryanmcdermott** [comment]
Hey there! Feel free to open a PR with a link to your forked repo. The translation links are at the bottom of the README.md. Just add yours there and I'll merge your PR.

**Comment by GMaiolo** [comment]
Keep us posted @tureey 
Thanks a lot @ryanmcdermott
