### ISSUE TITLE
that's different 

### ISSUE THREAD

**Issue by zhangenming** [ryanmcdermott/clean-code-javascript#260]
```
Bad: function createMicrobrewery(name) {
  const breweryName = name || 'Hipster Brew Co.'
  // ...
}
Good: function createMicrobrewery(name = 'Hipster Brew Co.') {
  // ...
}
```
when name is null createMicrobrewery(null)
the result  different

**Comment by GMaiolo** [comment]
> Be aware that if you use them, your function will only provide default values for undefined arguments. Other "falsy" values such as '', "", false, null, 0, and NaN, will not be replaced by a default value.

Did you read the description above the example?
