### ISSUE TITLE
Stop repeating console.log

### ISSUE THREAD

**Issue by Gurigraphics** [ryanmcdermott/clean-code-javascript#294]
### Stop repeating console.log

**Bad**:
```Js
console.log(a)
console.log(b)
console.log(c)
console.log(d)
```
**Good**:
```Js
const log = (v) => console.log(v)

log(a)
log(b)
log(c)
log(d)
```

**Comment by ryanmcdermott** [comment]
Hey there again! As mentioned, I only want to add subsections that have a corresponding one in the book Clean Code. I don't think this one does.

**Comment by Gurigraphics** [comment]
This is the most common example of "unnecessary code repetition". But ok.
