### ISSUE TITLE
Unnecessary closure/IIFE?

### ISSUE THREAD

**Issue by winek** [ryanmcdermott/clean-code-javascript#30]
In the advice about [private members](https://github.com/ryanmcdermott/clean-code-javascript/blob/master/README.md#make-objects-have-private-members), what's the point of the extra IIFE over `Employee` definition?

```js
var Employee = (function() {
  function Employee(name) {
    this.getName = function() {
      return name;
    };
  }

  return Employee;
}());
```

Since there are no extra variables in the outer function, this snippet could as well read:

```js
function Employee(name) {
  this.getName = function() {
    return name;
  };
 }
```

**Comment by ryanmcdermott** [comment]
Good point. I should have looked that over more closely. Now that I examine this more in depth, I think this section needs to be overhauled. Let's take a cue from the page below, and give this better treatment:

https://developer.mozilla.org/en-US/Add-ons/SDK/Guides/Contributor_s_Guide/Private_Properties

**Comment by ryanmcdermott** [comment]
Removing this in https://github.com/ryanmcdermott/clean-code-javascript/pull/95

Thanks for your help! Will also refactor to be a better subsection on private members.
