### ISSUE TITLE
Stale pull requests needs to be cleaned up

### ISSUE THREAD

**Issue by InfinitySamurai** [ryanmcdermott/clean-code-javascript#308]
Just a note that I was looking through some of the pull requests, and many of them are older than 2018. If they aren't relevant they should probably be closed. In particular #211 needs to be completely changed seeing as promises are now built in

**Comment by ryanmcdermott** [comment]
Sorry! I will get around to this as soon as I can. I don't have much free
time these days but I'll set aside some time when I can.
*----------------------------*
*Ryan McDermott*
*<Developer>*
*github.com/ryanmcdermott <https://github.com/ryanmcdermott>*

**Comment by InfinitySamurai** [comment]
All good mate, just another task to track. Real life takes precedence over free contributions to open source 👍
