### ISSUE TITLE
Use `const` and `let` over `var`

### ISSUE THREAD

**Issue by CodinCat** [ryanmcdermott/clean-code-javascript#31]
The current code samples are not consistent, mix a half `var` and a half `let` (and a few `const`).

We may need a unified rule for the usage of `const`/`let` and apply it to the code samples, as you mentioned in the second principle **Use ES6 constants when variable values do not change**, or your code is not *clean*. :wink:

**Comment by ryanmcdermott** [comment]
Thank you for sussing out the inconsistencies. We do need a coherent stance on this. @ericelliott has a [good article about this](https://medium.com/javascript-scene/javascript-es6-var-let-or-const-ba58b8dcde75), to use as inspiration so we could also elaborate more on the ES6 constants section.

**Comment by schoenwaldnils** [comment]
I even just started to edit for a PR, but then there were so much changes to make ^^

I highly recommend this screencast from laracast: 
https://laracasts.com/series/es6-cliffsnotes/episodes/3

I personally don't use `var` anymore and default to `const`.
And if the value changes, I change it to `let`.

**Comment by ryanmcdermott** [comment]
@schoenwaldnils has an awesome fix so I'm going to close this issue once that is merged in with minor tweaks. Thanks CodinCat for your help!

**Comment by ryanmcdermott** [comment]
This was addressed in #51. Thanks for all of your help!
