### ISSUE TITLE
Put the translation at the beginning of the article

### ISSUE THREAD

**Issue by b159732000** [ryanmcdermott/clean-code-javascript#350]
Please put the translation chapter at the beginning of the article to prevent any more stupid readers like me.
---
I opened two chrome tabs to read the article,
one in English and one in Chinese(using google translation).

After reading the entire article,
I found the Chinese version at the end of the article...

I saw the word translation in the outline,
but at the time I just thought it was an article,
teaching how to write translation code with clean code.

**Comment by ryanmcdermott** [comment]
Hey there, thank you for opening this! I prefer keeping the Translation section at the bottom as readers tend to drop off with more introductory sections being added. As you mention, the Translation section is still accessible from the Table of Contents! Feel free to open more issues in the future, I really appreciate your input.
