### ISSUE TITLE
I'm New here can anyone tell me how to find issue?

### ISSUE THREAD

**Issue by randhirshaw** [ryanmcdermott/clean-code-javascript#378]

**Comment by anthonychinwe** [comment]
Hello, you can search for issues by clicking on the `Issues` link on the top nav menu and tying only your desired keyword in the provided search field or by using qualifiers like `in:` , `is:`, `label:`, `author:`, `language:` etc, to filter the search results based on your chosen search keyword.
For more information, see; https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests

**Comment by randhirshaw** [comment]
Thank You! For this Precious information❤️💡.
