### ISSUE TITLE
method chaining - minor typo

### ISSUE THREAD

**Issue by cbinding** [ryanmcdermott/clean-code-javascript#41]
Nice work, very useful! In the section on 'method chaining', the setMake functions:

setMake(make) {  this.name = name;  }

should it be:

setMake(make) {  this.make = make;  }

**Comment by ryanmcdermott** [comment]
Duly noted! Thank you Ceri, if you want to make a PR feel free to anytime. I'll try to take care of this when I can.

**Comment by ryanmcdermott** [comment]
Closed after: d333e12d721e4ead46676e6b928facd3e96ccfb2
