### ISSUE TITLE
Legal comments in source files

### ISSUE THREAD

**Issue by lcseguin** [ryanmcdermott/clean-code-javascript#42]
You said: 
     Avoid legal comments in source files
     That's what your LICENSE file at the top of your source tree is for

I partially disagree.
1\ You can combine multiple licences in your source tree
2\ You can not expect that everyone will take all your files in their project (so with time, the original license can be lost)
3\ When someone snoop your code on your web-based stuff in production, the LICENSE file is often absent or not reachable.

So, as author, you must be absolutely clear about your licenses intentions, especially if you want protects freedom of users of your code users. Here some clue : 
https://www.gnu.org/philosophy/javascript-trap.html#AppendixA

**Comment by Calinou** [comment]
Indeed, in fact I was quite shocked when I saw this recommendation as the last one of the guide. It's a very common practice to add a license boilerplate at the top of each source file, and any smart IDE will hide it for you if you want.

**Comment by picsi** [comment]
Agreed per Calinou

**Comment by cookiengineer** [comment]
@lcseguin The problem I have with your argument is that you kind of are implying that everything by default is open source and can be reused. That's not the case, when a file has no LICENSE in it, you cannot reuse it as per copyright.

But I agree with the point that partial licensing might be an issue and needs a proper resolution. Instead of copy/pasting the same license, a one line header with MPL-2.0, MIT, GPL3 or whatever shortage and the copyright owners would do the trick because I think that's exactly what https://spdx.org/licenses/ is existing for.

**Comment by ryanmcdermott** [comment]
Thanks for your concerns and contributions Laurent!

I am not a lawyer, so I won't address how keeping a LICENSE out of each source file affects the freedom of the use thereof. In Clean Code, they actually suggest that Legal comments are good. I chose to go against that advice because many, many JavaScript libraries/projects just simply keep a LICENSE file in the top of the source tree. I don't know what the legal precedent is on it, and don't want to touch on that, therefore it's probably safer to get rid of this piece of advice.

All that said, I think I should remove this subsection, unless anyone has strong opinions to the contrary.

**Comment by Kasijjuf** [comment]
As far as code licensed under the GPL is concerned, allow me to direct your attention to the [Official GNU Licenses FAQ](https://www.gnu.org/licenses/gpl-faq.html) on GNU.org:

>**Why should I put a license notice in each source file?** ([#NoticeInSourceFile](https://www.gnu.org/licenses/gpl-faq.html#NoticeInSourceFile))
>
>You should put a notice at the start of each source file, stating what license it carries, in order to avoid risk of the code's getting disconnected from its license. If your repository's README says that source file is under the GNU GPL, what happens if someone copies that file to another program? That other context may not show what the file's license is. It may appear to have some other license, or no license at all (which would make the code nonfree).
>
>Adding a copyright notice and a license notice at the start of each source file is easy and makes such confusion unlikely.
>
>This has nothing to do with the specifics of the GNU GPL. It is true for any free license.
>
>**Is it enough just to put a copy of the GNU GPL in my repository?** ([#LicenseCopyOnly](https://www.gnu.org/licenses/gpl-faq.html#LicenseCopyOnly))
>
>Just putting a copy of the GNU GPL in a file in your repository does not explicitly state that the code in the same repository may be used under the GNU GPL. Without such a statement, it's not entirely clear that the permissions in the license really apply to any particular source file. An explicit statement saying that eliminates all doubt.
>
>A file containing just a license, without a statement that certain other files are covered by that license, resembles a file containing just a subroutine which is never called from anywhere else. The resemblance is not perfect: lawyers and courts might apply common sense and conclude that you must have put the copy of the GNU GPL there because you wanted to license the code that way. Or they might not. Why leave an uncertainty?
>
>This statement should be in each source file. A clear statement in the program's README file is legally sufficient as long as that accompanies the code, but it is easy for them to get separated. Why take a risk of uncertainty about your code's license?
>
>This has nothing to do with the specifics of the GNU GPL. It is true for any free license.

**Comment by lcseguin** [comment]
Hello @ryanmcdermott 

Being clear about the applicable terms of your code is very important, especially if you publish it. 
It is not a matter of free or non-free license, it's about the simple question "what can i do with this code?". As a developer, if i'm not absolutely certain that i can reuse/improve a code written by someone else, i don't use it (to protect myself and users of my code against any copyright claim).

I agree with you that putting 50 copyright/licence notice on the top of the file is not a good idea and everything must be in a LICENSE file. 

That why i suggest to improve your legal section with an advice to simply adding some minimal information on each file like : 

```
/*
  @licstart 
     Copyright (©) 2017 My[Company]Name
     Available under the terms of the GNU/LGPL-3.0
     See LICENSE file for more informations.
  @licend 
*/
```

**Comment by Tarabass** [comment]
At the company where I work we check every file (.cs, .js, .sql, etc.) for copyrights. This will break the build. I got my IDE's configured so they will add copyrights automatically on creating new files. It is very important to have your copyrights in every file.

We also have a license file, but we use that copyright information about software/libraries we use in our software. If we don't our software, which is not open source, will be open sourced automatically. Even though we have our copyrights in every file.

The funny part is that we add copyrights to our source code, but after uglifying/minifying our js all comments and copyrights are removed. So our production code that will be shipped has no copyright section (yet).

**Comment by cookiengineer** [comment]
> If we don't our software, which is not open source, will be open sourced automatically. Even though we have our copyrights in every file.

That is plain wrong. No license means the code is owned by its copyright holder; which was the author of the code as it's treated as "speech" or literature in front of the law.

**Comment by Tarabass** [comment]
I think, and I don't know much about this subject, that we keep the copyrights indeed. I didn't mean to say we weren't. I think that if we don't mention the authors etc. in our license file, our software can get the same license as GNU. Or something like that.

**Comment by lcseguin** [comment]
@Tarabass It is more complicated as that :-) If the original code is released under the terms of a copyleft license, you can't remove to others the freedom that you have benefit from the original work. For week copyleft license (as LGPL) it concern only the original code, for strong copyleft (as GPL) it concern all the aggregate where the code is (that's why you can't include GPL code in a software that is non-free or release under the terms of a license incompatible with the GPL).

But all of that discussion, is far away of "add a legal mention on your code" ;-)

**Comment by ryanmcdermott** [comment]
Since we are getting to thorny legal territory, and since Clean Code disagrees with what's stated in this document, I've removed this legal comments subsection. Thanks so much for raising these points!

ec8fd242cd3c073474fc2f3ec5c339344d5edacc
