### ISSUE TITLE
Explanation of 'const' does not convey mutability

### ISSUE THREAD

**Issue by arayi** [ryanmcdermott/clean-code-javascript#50]
In JS, `const` is NOT immutable—it can be *changed* but cannot be *reassigned*

(See https://mathiasbynens.be/notes/es6-const for a more detailed explanation)

I've seen this confuse many new devs, so I'd like to suggest including this information. I'll make a PR with the edit if you'd like. :tada:

**Comment by schoenwaldnils** [comment]
Thats why I opened a PR #51 
Maybe this issue is a duplicate to #31 ?

**Comment by arayi** [comment]
How is that addressed in PR #51 ?

See https://github.com/ryanmcdermott/clean-code-javascript#use-es6-constants-when-variable-values-do-not-change

This section seems to convey that `const` is for immutable values. "If the value changes, I change it to `let`" in #31 also seems to convey that `const` is for immutable values. So someone unfamiliar with how it is implemented may accidentally code something that modifies their `const` without reassigning it (which DOES work, unlike reassigning), and become very confused.

But no, this is not addressed in either of those.

**Comment by schoenwaldnils** [comment]
Sorry, I dind't meant that my PR changes the meaning of this paragraph. 
It just fixes the use of let and const in the readme itself.

The paragraph has to be rewritten, of course.

**Comment by tonytran1** [comment]
That's true, const properties can be changed and are mutable. The section was referring to primitive values of declared constants. Of course that's not their only use. Please update it to your understanding. Thanks.

**Comment by ryanmcdermott** [comment]
Thanks Arayi! You're right that the paragraph doesn't do the best job explaining the nature of the keyword `const` I think we should link to @mathiasbynens and @ericelliott for an authoritative educational stance on this. I would love a PR to accompany @schoenwaldnils awesome work!

**Comment by ryanmcdermott** [comment]
This subsection was removed for the time being, until we come up with a better explanation for when to prefer `const` and how it helps improve refactorability.

ac47e8231d32d4a8117a7539d6e75cb6e7483c80
