### ISSUE TITLE
ES version for async functions

### ISSUE THREAD

**Issue by darahak** [ryanmcdermott/clean-code-javascript#52]
First, thanks a lot for this guide. Love it!
I just wanted to point out one little mistake.

> Promises are a very clean alternative to callbacks, but ES7 brings async and await which offer an even cleaner solution. All you need is a function that is prefixed in an async keyword, and then you can write your logic imperatively without a then chain of functions. Use this if you can take advantage of ES7 features today!

Actually ES2016 (or ES7) only added two features: `Array.prototype.includes` and the exponentiation operator.

Async/Await is featured in [ES2017](https://github.com/tc39/proposals/blob/master/finished-proposals.md) (or ES8).

**Comment by ryanmcdermott** [comment]
I'm really glad this has been helpful!

Interesting, I didn't realize the standards committee hadn't approved that. Can you send a PR for that? If not, no worries!

For everyone's reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/New_in_JavaScript/ECMAScript_Next_support_in_Mozilla

**Comment by darahak** [comment]
Sure, I'll make a PR :+1: 
Do you want to keep the ES5/6/7/... form or switch to the new one with the yearly releases?
Maybe both for the people who might not be aware of the correlation?

**Comment by ryanmcdermott** [comment]
Haha good! Get rest, code ends up cleaner that way :)

So how about we just do a simple change with the wording and say it would be an ES2017/ES8 feature?
