### ISSUE TITLE
May I translate it in Chinese ?

### ISSUE THREAD

**Issue by alivebao** [ryanmcdermott/clean-code-javascript#55]
Hi, may I translate it in Chinese and put on network？

**Comment by MicroBenz** [comment]
Same question here.
But I will translate it in Thai instead.

**Comment by magicdawn** [comment]
FYI: I just saw a MIT LICENSE file https://github.com/ryanmcdermott/clean-code-javascript/blob/master/LICENSE

**Comment by ryanmcdermott** [comment]
Yes of course! Any translations would be absolutely wonderful. Thank you!

**Comment by fesnt** [comment]
Starting translating to Brazilian Portuguese - https://github.com/fesnt/clean-code-javascript

**Comment by ryanmcdermott** [comment]
Hey @fesnt! Let me know when this is ready. I'll link it a *Translation* section at the bottom of the project.

**Comment by fesnt** [comment]
@ryanmcdermott the translation is ready!

**Comment by ryanmcdermott** [comment]
@fesnt Cool! Can you open a PR and use the same format as AirBnB's style guide for translations? https://github.com/airbnb/javascript#translation
