### ISSUE TITLE
Unorganized list is numeric

### ISSUE THREAD

**Issue by k1sul1** [ryanmcdermott/clean-code-javascript#78]
There's an ordered list in "Ojects and Data structures" section, but it says  "Well, here's an unorganized list of reasons why" right before the list starts. 

So which one is it? This could be a major issue for someone :)

https://github.com/ryanmcdermott/clean-code-javascript/blob/master/README.md#objects-and-data-structures

**Comment by ryanmcdermott** [comment]
Duly noted and duly fixed in 50850a937040c341f7ec8aff95b5293b046081a0

Thank you!
